# Generated by Django 6.0.4 on 2026-04-25 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendation', '0001_initial'),
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationbatch',
            name='scan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_batch', to='scan.scan'),
        ),
        migrations.AddField(
            model_name='recommendationitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recommendation.recommendationbatch'),
        ),
    ]
