# Generated by Django 6.0.4 on 2026-04-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('food', 'Food'), ('cosmetic', 'Cosmetic')], max_length=32)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('extraction_method', models.CharField(choices=[('lens', 'Lens'), ('barcode', 'Barcode')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
