# Generated by Django 5.1.3 on 2026-05-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('cosmetic', 'Cosmetic'), ('unknown', 'Unknown')], max_length=32),
        ),
    ]
