# Generated by Django 5.1.3 on 2026-05-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extraction_method',
            field=models.CharField(choices=[('lens', 'Lens'), ('barcode', 'Barcode'), ('unknown', 'Unknown')], max_length=32),
        ),
    ]
